# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  store-postgresql:
    image: postgres:14.3
    volumes:
      - /var/lib/docker/volumes/base_store/_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
  #    ports:
  #      - 5432:5432
  #    networks:
  #      - store-net
  store-app:
    image: store
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://store-postgresql:5432/store
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://store-postgresql:5432/store
      - JHIPSTER_SLEEP=5 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 8080:8080
#    networks:
#      - store-net

networks:
  store-net:
    driver: bridge
